; OpenGL Primitives
%define GL_FALSE                        0x0
%define GL_TRUE                         0x1

%define GL_TRIANGLES                    0x4

%define GL_UNSIGNED_INT                 0x1405
%define GL_FLOAT                        0x1406


%define GL_SMOOTH                       0x1D01
%define GL_DEPTH_TEST                   0x0B71
%define GL_LEQUAL                       0x0203
%define GL_PERSPECTIVE_CORRECTION_HINT  0x0C50
%define GL_NICEST                       0x1102

%define GL_NO_ERROR                     0x0
%define GL_DEBUG_OUTPUT                 0x92e0

%define GL_COLOR_BUFFER_BIT             0x00004000
%define GL_DEPTH_BUFFER_BIT             0x00000100

; glGetString constants
%define GL_VENDOR                       0x1f00
%define GL_RENDERER                     0x1f01
%define GL_VERSION                      0x1f02
%define GL_SHADING_LANGUAGE_VERSION     0x8b8c

%define GL_ARRAY_BUFFER                 0x8892
%define GL_ELEMENT_ARRAY_BUFFER         0x8893

%define GL_STATIC_DRAW                  0x88e4

; Shader constants
%define GL_FRAGMENT_SHADER              0x8b30
%define GL_VERTEX_SHADER                0x8b31

%define GL_COMPILE_STATUS               0x8b81
%define GL_LINK_STATUS                  0x8b82

